updated iota libraries
iotaledger/tangle.js pull request #11
Opened 2021-11-08 16:08 UTC by 7opf

# Description of change

* Adds support for `--devnet` option for `vc` and `did` commands #3
* Adds support for `--net-id` option for `vc` and `did` commands to specify a (private) Tangle network ID #3
* Adds new options to specify the explorer `-e` and permanode `-p` URLs when using `-n`
* Updated `@iota/identity-wasm` to 0.4.0
* Updated `@iota/iota.js` to 1.8.1
* Added dependency `@iota/util.js` (previously part of `@iota/iota.js`)
* Bumped version to 0.10.0

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

```
# mainnet
node ./dist/tcli did create --mainnet
node ./dist/tcli did resolve --did "did:iota:XYZ" --mainnet

node ./dist/tcli vc issue --issuer "did:iota:XYZ" --secret "ABC" --subject "did:iota:XYZ" --method "#authentication" --claims '{ ""gender"": ""male"" }' --mainnet

# devnet
node ./dist/tcli did create --devnet
node ./dist/tcli did resolve --did "did:iota:dev:XYZ" --devnet

node ./dist/tcli vc issue --issuer "did:iota:dev:XYZ" --secret "ABC" --subject "did:iota:dev:XYZ" --method "#authentication" --claims '{ ""gender"": ""male"" }' --devnet

# private tangle
node ./dist/tcli did create -n http://one-click-tangle:14265 -e http://one-click-tangle:8081/explorer --net-id tangle
node ./dist/tcli did resolve --did "did:iota:tangle:XYZ" -n http://one-click-tangle:14265 -e http://one-click-tangle:8081/explorer --net-id tangle

node ./dist/tcli vc issue --issuer "did:iota:tangle:XYZ" --secret "ABC" --subject "did:iota:tangle:XYZ" --method "#authentication" --claims '{ ""gender"": ""male"" }' -n http://one-click-tangle:14265 -e http://one-click-tangle:8081/explorer --net-id tangle
```

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2021-11-08 16:13 UTC, 7opf commented
I think `--net` should be renamed to `--node` in a future breaking change updated.

2021-11-11 10:54 UTC, peterokwara commented
When creating a DID on a private tangle using one-click-tangle, by default the route should be http://x.x.x.x:8082/tangle see https://github.com/iotaledger/one-click-tangle/pull/60#issuecomment-954543650

As notes

2021-11-11 11:03 UTC, 7opf commented
> When creating a DID on a private tangle using one-click-tangle, by default the route should be http://x.x.x.x:8082/tangle see [iotaledger/one-click-tangle#60 (comment)](https://github.com/iotaledger/one-click-tangle/pull/60#issuecomment-954543650)
> 
> As notes

@peterokwara Is the explorer always mounted on path `/tangle` or is it based on the network ID? e.g. `/sevnet`?

2021-11-11 12:40 UTC, peterokwara commented
As of now @7opf  the explorer is always mounted on the path **/tangle**
To change the path to be for example **/SevTangle**
![image](https://user-images.githubusercontent.com/6847405/141299417-f29faac5-b162-4e20-ac06-910f2d9af84a.png)
You would need to change this line https://github.com/iotaledger/one-click-tangle/blob/cd9b1501701b21f6bf6c9d17d61990bd5661860f/explorer/config/private-network.json#L2 to be **SevTangle**

2021-11-11 12:57 UTC, 7opf commented
Since the URL of a private tangle's explorer depends on the deployment configuration of the explorer, I won't change anything in this PR, unless I'm misunderstanding something? I've added the `-e` option to specify the base href of the explorer for this reason.  
As it is now, the `--mainnet` and `--devnet` flags are just convenience flags to automatically set `-n`, `-e` and `-p` and `--net-id` options. What I could do is add an additional convenience flag such as `--oct` which sets these options to the expected values if one were to set up a local one-click-tangle deployment with default settings.

2021-11-11 14:47 UTC, peterokwara commented
Yeah you don't need to change anything in the code or in the PR. Or even the flags. It's okay the way it is.

2021-11-17 10:15 UTC, jmcanterafonseca-iota requested changes
we need several improvements and also to set up prettier as in other codebases

2021-11-17 10:15 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/src/commands/did/createDidCommandExecutor.ts
> +      transactionUrl: `${netParams.explorer}/message/${receipt.messageId}`
same comment as above

2021-11-17 10:15 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/src/commands/did/didCommand.ts
> +    name: "net-id",
see comments about refactoring params

2021-11-17 10:15 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/src/commands/msg/submitMsgCommandExecutor.ts
> +import {
we need a prettier setup aligned with what @obany is doing in other codebases so that there are no discrepancies on prettifying code

2021-11-17 10:15 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/src/commands/vc/vcCommand.ts
> +  {
don't repeat this definition, it should be in one place, modulo the comments made before

2021-11-17 10:20 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/package.json
> +  "version": "0.10.0",
as we will be making a little breaking change 0.10.0 would be fine though

2021-11-17 10:35 UTC, 7opf commented on tools/tangle-cli/src/commands/channel/anchorMsgCommandExecutor.ts
> +        explorerURL: `${explorer}/message/${msgIDLayer1}`
It is in the [Tangle Explorer client](https://github.com/iotaledger/explorer/blob/dev/client/src/app/App.tsx#L254-L259). Technically, the network ID could also be taken out such that the URL is constructed like this:
```
${explorer}/${network}/message/${msgIDLayer1}
```

2021-11-17 10:36 UTC, 7opf commented on tools/tangle-cli/package.json
> +  "version": "0.10.0",
In that case I will keep it as 0.10.0.

2021-11-23 07:41 UTC, jmcanterafonseca-iota commented
still errors and warnings while building @7opf

2021-11-23 07:42 UTC, jmcanterafonseca-iota requested changes
this needs more work

2021-11-23 07:56 UTC, jmcanterafonseca-iota requested changes

2021-11-23 07:56 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/.prettierignore
> +.eslintrc.js
new line needed

2021-11-23 07:56 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/CHANGELOG.md
> +- Support for private tangles is now possible using the new options above.
```suggestion
- Support for Private Tangle is now possible using the new options above.
```

2021-11-23 07:56 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/README.md
> +  --devnet         Default settings for IOTA Chrysalis Devnet
instead of repeating this info across all the document it would be better to have it one time at the beginning of the README

2021-11-23 07:56 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/package.json
> +    "build": "npm-run-all build-format build-clean build-compile build-lint",
```suggestion
    "build": "npm-run-all  build-clean build-format build-compile build-lint",
```

2021-11-23 12:05 UTC, jmcanterafonseca-iota approved these changes
Now looks good to me, please check some suggestions on parameters aliases

2021-11-23 12:22 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/CHANGELOG.md
> +- New options to specify custom explorer URL (`--explorer, -e`), permanode URL (`--permanode, -p`) and network ID (`--net, -i`). See changes below regarding `--net`.
if we finally change the alias, this would have to be tweaked

2021-11-23 12:23 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/scripts/generate-readme.sh
> +
add a comment to describe the purpose of this script

2021-11-23 12:29 UTC, jmcanterafonseca-iota commented on tools/tangle-cli/package.json
> +    "scripts": {
it would be good if we could run the README generator from here as well

2021-11-23 16:58 UTC, jmcanterafonseca-iota approved these changes
LGTM

2021-11-23 16:59 UTC, merged